### ISSUE TITLE
Error in generating javadoc using built in and System generator

### ISSUE THREAD

**Issue by AmanRathoreM** [KeeganBruer/javadoc-generator#15]
![Please if you know the solution to this problem please tell](https://user-images.githubusercontent.com/83628481/140012047-6a840322-08d7-4255-af44-cfcb1d2e619d.png)
![Please if you know the solution to this problem please tell](https://user-images.githubusercontent.com/83628481/140012103-05bfb1b1-b052-4067-b943-f0f96dc464e0.png)

**Comment by KeeganBruer** [comment]
Sorry for the issue arising. I've realized this extension doesn't have good error reporting so it is hard to tell where this issue stems from. It also had some strict paths that caused errors if you didn't have your machine configured the right way.

I have been working on a new version that adds a lot more customization options and should help with these issues. 
Let me know if you are still getting this same issue with the new version and I'll try and fix it.
