### ISSUE TITLE
Issue with generating documents

### ISSUE THREAD

**Issue by vinod1967** [KeeganBruer/javadoc-generator#16]
![image](https://user-images.githubusercontent.com/86562541/141251755-112bcc57-92c4-40d8-95b5-979681142884.png)
![image](https://user-images.githubusercontent.com/86562541/141251975-fec22da8-c163-4264-b035-e20d01df6575.png)

**Comment by rkamalakannan** [comment]
I have the same issue as well.. :(

**Comment by Osomhe1** [comment]
I have same issue as well @rkamalakannan  has yours been resolve? If yes how did you do it?
Thanks in advance.

**Comment by rkamalakannan** [comment]
Hi

Not yet.  I had not fixed it yet.

**Comment by KeeganBruer** [comment]
Sorry for the issue arising. I've realized this extension doesn't have good error reporting so it is hard to tell where this issue stems from. It also had some strict paths that caused errors if you didn't have your machine configured the right way.

I have been working on a new version that adds a lot more customization options and should help with these issues. 
Let me know if you are still getting this same issue with the new version and I'll try and fix it.
