### ISSUE TITLE
Generate with built in tool

### ISSUE THREAD

**Issue by ThedeathButher** [KeeganBruer/javadoc-generator#17]
![image](https://user-images.githubusercontent.com/93651404/158143859-cbb795fc-5ac2-48dc-ad7d-2def95a24134.png)
What is the issue, or am I doing something wrong?

Edit: Didn´t install "Javadoc.exe"

**Comment by ThedeathButher** [comment]
Still doesn´t work. Same mistake.

**Comment by KeeganBruer** [comment]
Hey, just waking up. I'll post a fix within the hour

**Comment by KeeganBruer** [comment]
@ThedeathButher  Alright, I just pushed version 2.0.2. That should fix your issues with the built-in version of the javadoc. If this doesn't fix it completely, I have another idea for why it may not work on some machines. If you don;t see the new version, give it a few moments. Microsoft is probably taking a while to verify the changes.

**Comment by ThedeathButher** [comment]
The changes seem to work, but now I´ve got a different error message.
![image](https://user-images.githubusercontent.com/93651404/158226901-753f90da-c213-4b98-931d-da64d235f176.png)
Is it possible that I am doing something wrong?
Thank you in advance

**Comment by KeeganBruer** [comment]
@ThedeathButher in this new update, you no longer have to type in "built in" just leave that blank

**Comment by KeeganBruer** [comment]
Assuming that this issue has been resolved. Please reopen or post a new issue if you continue to have problems.
