### ISSUE TITLE
Issues with Javadoc generator 

### ISSUE THREAD

**Issue by kalvinliang965** [KeeganBruer/javadoc-generator#25]
When I was using the javadoc generator, it said no JAVA_HOME was found in the path, but it didn't  prompt me for a JDK install directory, and I do have one. Then, it said javadoc was generated successfully but there are these error:

At line:1 char:107
+ ... .javadoc-generator-2.0.2/dependencies/jdk/bin/javadoc.exe" -d 
"d:\Des ...
+                                                                ~~ 
Unexpected token '-d' in expression or statement.
At line:1 char:110
+ ... doc.exe" -d 
"d:\Desktop\VSCode-For-Java\MyFirstProject/src\javadoc" - ...       
+
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Unexpected token 
'"d:\Desktop\VSCode-For-Java\MyFirstProject/src\javadoc"' in expression  
or statement.
At line:1 char:166
+ ... sktop\VSCode-For-Java\MyFirstProject/src\javadoc" -sourcepath      
"d:\Des ...
+                                                       ~~~~~~~~~~~      
Unexpected token '-sourcepath' in expression or statement.
At line:1 char:178
+ ... " -sourcepath "d:\Desktop\VSCode-For-Java\MyFirstProject/src"      
-subpac ...
+                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~      
Unexpected token '"d:\Desktop\VSCode-For-Java\MyFirstProject/src"' in    
expression or statement.
At line:1 char:226
+ ... urcepath "d:\Desktop\VSCode-For-Java\MyFirstProject/src" 
-subpackages
+
~~~~~~~~~~~~
Unexpected token '-subpackages' in expression or statement.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorR  
   ecordException
    + FullyQualifiedErrorId : UnexpectedToken

**Comment by Wii-Tu-Hi** [comment]
I also have this same error code and issues with JAVA_HOME, hoping for a fix as Java Documentation was introduced in my class this week and I expect more in the future.
![1](https://github.com/KeeganBruer/javadoc-generator/assets/120297192/bb35ec30-284f-4467-925e-64032bc9dbd8)

**Comment by gcgcgcgc** [comment]
Remove the double quotes around the executable and it will work.

**Comment by KeeganBruer** [comment]
I believe the issue in this case is that the path uses both a forward slash and a backward slash. I've just published version 3, which should resolve this issue by not using string concatenation for path resolution. If you upgrade, the config file adds a good amount of transparency to the underlying javadoc command that's being run.

**Comment by KeeganBruer** [comment]
With the release of Version 3, this should no longer be an issue. So I am going to close this. If you continue to have issues, please update to the latest extension version and then submit a new issue with the "config.jdgenerator" included.
