### ISSUE TITLE
"undefined/bin/javadoc" VSCode mac

### ISSUE THREAD

**Issue by CuAnnan** [KeeganBruer/javadoc-generator#26]
Installed by the market place within vscode.
Attempted to follow instructions.

"undefined/bin/javadoc" -public -d "/Users/wing/Documents/CS171/CS 171 Project/CS 171 Project/javadoc" -sourcepath "/Users/wing/
Documents/CS171/CS 171 Project/CS 171 Project/src" -subpackages cs171

**Comment by KeeganBruer** [comment]
It looks like it was unable to find a location for the JDK, you should be able to run the command with "Built In" to use the JDK shipped with the extension.

**Comment by KeeganBruer** [comment]
The new version of this extension provides better insight into this issue by providing the location of the Java Home in the config file generation. If you have this issue again, please make sure you've update the the latest version and submit a new issue with your "config.jdgenerator" file.
