### ISSUE TITLE
After install don't get "Javadoc Tools: Export Javadoc"

### ISSUE THREAD

**Issue by gcgcgcgc** [KeeganBruer/javadoc-generator#27]
After installation only the "Javadoc Tools: Generate Javadoc Comments for Workspace" item is available. The other items don't appear.

I would like to use the item "Javadoc Tools: Export Javadoc" but I don't know how to make it appear.

VS Code is the package for the "FIRST Robotics Competition" "WPILib" installer
Version: 1.85.1
Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
Date: 2023-12-13T09:49:37.021Z
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045

**Comment by KeeganBruer** [comment]
You can see how to use the latest release here:
https://github.com/KeeganBruer/javadoc-generator/blob/2.0.0/README.md

I believe the command your looking for is: "Javadoc Generator: Generate Javadoc". 

Unfortunately, It has some major bugs as it was originally intended for personal use. I a currently rebuilding with a better foundation.

**Comment by KeeganBruer** [comment]
As of now, I've just published version 3! If you upgrade, the config file adds a good amount of transparency to the underlying javadoc command that's being run. And the new setup process is easier and more intuitive, 

Also, WPILib takes me back to when I wrote version 1 for my own FRC team's java code. haha.

**Comment by KeeganBruer** [comment]
I am going to close this issue as I believe it is more related to the confusion between "Javadoc Generator" and the "Javadoc-Tools" extension. I am not familiar with the other extension so there may be a way to generate the javadoc using this other extension, but i do not know.
