### ISSUE TITLE
Javadoc executable validation

### ISSUE THREAD

**Issue by LeducNic** [KeeganBruer/javadoc-generator#30]
On MacOS and Linux, the Javadoc executable don't ends with .exe

**Comment by KeeganBruer** [comment]
Ah, I knew I missed something. Good catch. I'll push a change in just a minute.

**Comment by KeeganBruer** [comment]
@LeducNic Changes pushed to marketplace. Should be available in a few minutes.

**Comment by LeducNic** [comment]
Thank you for your excellent work.  You are really fast. :)

About the executable, you still append the .exe when you add it to the config file even when we are on MacOS / Linux so the suggested executable is invalid.  At least the detected path is correct, so I need to remove the .exe manually to make it work.

**Comment by KeeganBruer** [comment]
Oh, man. I keep missing these small things. Thanks for pointing them out. I'll add a way to detect system and append the correct extension for the executable.

**Comment by LeducNic** [comment]
Maybe you could just check if the executable exist with .exe and if not just remove the .exe when you create the config file.  You already make the check when the config file is saved.  That way you could avoid more complex checks?

**Comment by KeeganBruer** [comment]
Love it. I'll get that added tonight

**Comment by KeeganBruer** [comment]
I believe this issue has been addressed and given there is no follow ups. I will close this for now.

Thank you for helping to improve this extension!
