### ISSUE TITLE
Add field for custom command line switches

### ISSUE THREAD

**Issue by LeducNic** [KeeganBruer/javadoc-generator#31]
It would be useful to add a field in the json that let us write command line parameters that are not automatically generated by your script.  For example, I want to specify to export only public or private class members. Also, I need to give the correct classpath to avoid export errors.  So a field like:

"extra params" : "-public -cp junit.jar"

added to the json and inserted after the -o argument would be interesting.  Maybe some tests would be needed to confirm the order of arguments

By the way, excellent work! Thank a lot for maintaining this extension.

**Comment by KeeganBruer** [comment]
Great Idea! I'll add it to the board. I was going to try and add every parameter as a config to the json. but that's a good way to support it in the meantime. I'll add that tonight.

**Comment by KeeganBruer** [comment]
Feature added. I decided "raw_params" fit better with the future naming scheme. I'm going to close this issue for now, feel free to reopen if issues arise.

**Comment by LeducNic** [comment]
Hello,

     A space is missing between rawParam and filteredFiles on line 172:
return `${javadoc_executable} ${sourcepath} ${distpath} ${rawParams}${filteredFiles.join(" ")}`;
and maybe two lines before also.

    Right now I have to add a space at the end of my raw param list to "fix" that.

Have a great day
Nicolas
