### ISSUE TITLE
Not sure where my javadocs are being saved

### ISSUE THREAD

**Issue by Atom-Cunningham** [KeeganBruer/javadoc-generator#4]
I'm having trouble with JDK on eclipse so I tried your tool.
However, after running the auto-generator and allowing it to complete,
I am unable to locate the javadoc.
I expected to find it either in my src or in my working repository.
What is the path where I should expect the html file to be saved to?

**Comment by KeeganBruer** [comment]
It should compile into your project folder (the folder your src folder is in) under folder name "javadoc".
