### ISSUE TITLE
Usage with C++?

### ISSUE THREAD

**Issue by am8525** [KeeganBruer/javadoc-generator#6]
Hello,

Wanting to use your plugin with my C++ source code, which currently does not seem to be possible. Could you foresee adding this on as a feature, or sharing your design methodology so I could try implementing it myself?

Cheers.

**Comment by KeeganBruer** [comment]
This plugin currently is just a wrapper for the javadoc compiler which is developed by the official Java team. I'm just creating a plugin that runs it on the current workspace folder. I could foresee adding other language capabilities but am currently attending uni and this would have to be in my off time. 
My favorite documentation generator for c++ is doxygen so I may add support for this in the plugin soon.
